config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: ''
  resources :notes
  resources :images, only: :create
  root 'notes#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  has_one_attached :attachment
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  scope :recent, -> { where('published_on is not ?', nil).order(published_on: :desc) }
  scope :drafts, -> { where('published_on is ?', nil).order(created_at: :desc) }

  with_options presence: true do
    validates :title
    validates :body
  end

  def body_to_html
    Kramdown::Document.new(body, input: 'GFM').to_html
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, # :registerable, :recoverable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  def create
    @image = Image.new(attachment: params[:file])

    if @image.save
      render json: { url: rails_blob_url(@image.attachment) }, status: :created
    else
      render json: @image.errors, status: :unprocessable_entity
    end
  end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_note, only: %i[show edit update destroy]

  def index
    @notes = Note.recent
    @drafts = Note.drafts
  end

  def show; end

  def new
    @note = Note.new
  end

  def edit; end

  def create
    @note = Note.new(note_params)

    if @note.save
      redirect_to note_url(@note), notice: 'Note was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @note.update(note_params)
      redirect_to note_url(@note), notice: 'Note was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @note.destroy

    redirect_to notes_url, notice: 'Note was successfully destroyed.'
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body, :published_on)
  end
end

app/controllers/users/devise_controller.rb
# frozen_string_literal: true

class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_flash.html.slim
.text-center
  p[style="color: green"]
    = notice
  p[style="color: red"]
    = alert

app/views/application/_footer.html.slim
.footer
  = "© #{Time.zone.now.year} ruanshiron"

app/views/application/_header.html.slim
= link_to root_path do
  h1.text-center Ruanshiron
- if user_signed_in?
  .text-center
    = link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete } 
br

app/views/application/_lumos.html.slim
.text-end
  span#lumos data-controller='lumos'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Ruanshiron
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
  body
    .container
      = render "lumos"
      = render "header"
      = render "flash"
      = yield
      = render "footer"

app/views/notes/_form.html.slim
= form_with(model: note) do |form|
  .field
    = form.label :title, style: "display: block"
    = form.text_field :title
    - form.object.errors.full_messages_for(:title).each do |message|
      .invalid-feedback
        = message
  .field
    = form.label :published_on, style: "display: block"
    = form.date_field :published_on
  .field
    = form.label :body, style: "display: block"
    = form.text_area :body, data: { controller: 'textarea' }
    - form.object.errors.full_messages_for(:title).each do |message|
      .invalid-feedback
        = message
  .field
    = form.submit

app/views/notes/_note.html.slim
.note id=dom_id(note)
  = link_to note do
    h2
      = note.title
  p
    = note.published_on
  div
    == note.body_to_html

app/views/notes/edit.html.slim
.text-center
  = link_to "Show this note", @note
br
= render "form", note: @note

app/views/notes/index.html.slim
- if user_signed_in?
  = link_to "New note", new_note_path
#drafts
  = render @drafts
#notes
  = render @notes

app/views/notes/new.html.slim
h2.text-center
  | New note
= render "form", note: @note

app/views/notes/show.html.slim
- if user_signed_in?
  .text-center
    = link_to "Edit this note", edit_note_path(@note)
= render @note
- if user_signed_in?
  .danger-zone.text-end
    span
      | Feel bored?
    = button_to "Destroy this note", @note, method: :delete, form: { data: { turbo_confirm: "Are your sure to destroy this note?" } }